# Generated by Django 5.1.2 on 2024-10-20 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_mytest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyTest',
        ),
    ]
