# Generated by Django 5.1.2 on 2024-11-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_mytest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'حساب کاربری', 'verbose_name_plural': 'حساب های کاربری'},
        ),
    ]
