# Generated by Django 5.1.2 on 2024-10-19 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(choices=[('A', 'پایتون'), ('B', 'جنگو')], max_length=70),
        ),
    ]
