# Generated by Django 5.1.2 on 2024-10-19 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_article_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 19, 27, 38, 774851, tzinfo=datetime.timezone.utc)),
        ),
    ]
