# Generated by Django 5.1.2 on 2024-10-19 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 21, 52, 4, 21614, tzinfo=datetime.timezone.utc)),
        ),
    ]
