# Generated by Django 5.1.2 on 2024-10-20 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_pub_date_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyTest',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 20, 0, 20, 44, 856902, tzinfo=datetime.timezone.utc)),
        ),
    ]
