# Generated by Django 5.1.2 on 2024-10-19 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_article_is_published_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_published',
            field=models.DurationField(default=datetime.timedelta(days=23, seconds=78234)),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 15, 57, 10, 325480, tzinfo=datetime.timezone.utc)),
        ),
    ]
