# Generated by Django 5.1.2 on 2024-10-19 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_alter_article_is_published_alter_article_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='is_published',
        ),
        migrations.AddField(
            model_name='article',
            name='floatfield',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 16, 7, 53, 827758, tzinfo=datetime.timezone.utc)),
        ),
    ]
