# Generated by Django 5.1.2 on 2024-10-19 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_remove_article_is_published_article_floatfield_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='myfile',
            field=models.BinaryField(null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 19, 16, 26, 2, 409530, tzinfo=datetime.timezone.utc)),
        ),
    ]
