# Generated by Django 5.1.2 on 2024-10-23 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_alter_article_myfile_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 23, 18, 3, 53, 289131, tzinfo=datetime.timezone.utc)),
        ),
    ]
