# Generated by Django 5.1.2 on 2024-10-23 19:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_new_alter_article_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 23, 19, 5, 16, 24015, tzinfo=datetime.timezone.utc)),
        ),
    ]
