# Generated by Django 5.1.2 on 2024-10-24 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_article_status_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2024, 10, 24, 9, 17, 1, 94641, tzinfo=datetime.timezone.utc)),
        ),
    ]
