# Generated by Django 5.1.2 on 2024-10-24 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_remove_article_pub_date_alter_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='floatfield',
        ),
    ]
