# Generated by Django 5.1.2 on 2024-10-29 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_remove_article_floatfield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'post', 'verbose_name_plural': 'stories'},
        ),
    ]
