# Generated by Django 5.1.2 on 2024-10-29 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0035_alter_article_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={},
        ),
    ]
