# Generated by Django 5.1.2 on 2024-10-29 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0039_alter_comment_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created',
            new_name='created_at',
        ),
    ]
