# Generated by Django 5.1.2 on 2024-11-16 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0047_alter_article_author_alter_article_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 13, 50, 46, 319223, tzinfo=datetime.timezone.utc)),
        ),
    ]
