# Generated by Django 5.1.2 on 2024-11-16 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_alter_article_image_alter_article_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 17, 5, 39, 167556, tzinfo=datetime.timezone.utc)),
        ),
    ]
