# Generated by Django 5.1.2 on 2024-11-16 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0052_alter_article_pub_date_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 16, 17, 39, 39, 869986, tzinfo=datetime.timezone.utc)),
        ),
    ]
